import type { Request, Response } from "express";
import { z } from "zod";
import { asyncHandler } from "../lib/asyncHandler";
import type { AIService } from "../services/aiService";
import { prisma } from "../prisma/client";
import { AppError } from "../lib/errors";

const chatPayloadSchema = z.object({
  conversationId: z.string().trim().min(1).optional(),
  message: z.string().trim().min(1),
});

const idParamSchema = z.object({
  id: z.string().trim().min(1),
});

const sendSseChunk = (res: Response, event: string, payload: unknown) => {
  const serialized = JSON.stringify(payload);
  res.write(`event: ${event}\n`);
  res.write(`data: ${serialized}\n\n`);
};

export const createAIController = (aiService: AIService) => ({
  chat: asyncHandler(async (req: Request, res: Response) => {
    const body = chatPayloadSchema.parse(req.body);
    const auth = req.auth;

    if (!auth) {
      throw new AppError("Authentication required.", 401);
    }

    const tenant = await prisma.tenant.findUnique({
      where: { id: auth.tenantId },
    });

    // Debug tenant lookup in tests.
    // eslint-disable-next-line no-console
    console.log("aiController.chat tenant lookup", auth.tenantId, tenant);

    if (!tenant) {
      throw new AppError("Tenant not found.", 404);
    }

    const title = body.conversationId
      ? undefined
      : body.message.split(/\s+/).slice(0, 8).join(" ").trim() || "AI conversation";

    const conversation = body.conversationId
      ? await aiService.ensureConversationBelongsToTenant(auth.tenantId, body.conversationId)
      : await aiService.createConversation(auth.tenantId, auth.userId, title as string);

    await aiService.saveUserMessage(conversation.id, body.message);

    res.setHeader("Content-Type", "text/event-stream");
    res.setHeader("Cache-Control", "no-cache");
    res.setHeader("Connection", "keep-alive");
    res.setHeader("X-Accel-Buffering", "no");
    res.flushHeaders();

    const { stream: assistantStream, toolCalls } = await aiService.streamAssistantReply(
      auth.tenantId,
      auth.userId,
      tenant.name ?? "AIHub",
      tenant.industry,
      conversation.id,
      body.message,
      (event, payload) => {
        sendSseChunk(res, event, payload);
      }
    );

    let assistantText = "";
    let streamingError: Error | null = null;

    try {
      for await (const chunk of assistantStream) {
        assistantText += chunk;
      }

      res.write("event: done\ndata: [DONE]\n\n");
      await aiService.saveAssistantMessage(
        conversation.id,
        assistantText,
        "Assistant reply generated by Gemini.",
        toolCalls
      );
      res.end();
    } catch (error) {
      streamingError = error instanceof Error ? error : new Error("Unknown streaming error.");
      sendSseChunk(res, "error", { message: streamingError.message });
      res.write("event: done\ndata: [DONE]\n\n");
      res.end();
      throw streamingError;
    }
  }),

  listConversations: asyncHandler(async (req: Request, res: Response) => {
    const auth = req.auth;

    if (!auth) {
      throw new AppError("Authentication required.", 401);
    }

    const conversations = await aiService.listConversationsForUser(auth.tenantId, auth.userId);
    res.json({ conversations });
  }),

  getConversation: asyncHandler(async (req: Request, res: Response) => {
    const { id } = idParamSchema.parse(req.params);
    const auth = req.auth;

    if (!auth) {
      throw new AppError("Authentication required.", 401);
    }

    const conversation = await aiService.ensureConversationBelongsToTenant(auth.tenantId, id);
    const messages = await aiService.listMessagesForConversation(conversation.id);

    res.json({ conversation, messages });
  }),
});
